language: go
dist: bionic
arch:
  - amd64
go:
  - 1.17.x
  - 1.16.x
  - 1.15.x
  - 1.14.x
  - 1.13.x
install:
  - go get -u github.com/triplewz/poseidon
script:
  - go test -v ./bls12_381/... --bench=. -cover
  - go test -v --bench=. -cover
